# Generated by Django 5.0.7 on 2024-08-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_system', '0003_alter_vote_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='open_to_vote',
            field=models.BooleanField(default=True),
        ),
    ]
