# Generated by Django 5.0.7 on 2024-08-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_selected_avatar',
            field=models.BooleanField(default=False),
        ),
    ]
