# Generated by Django 5.0.7 on 2024-08-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_avatar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(default=(1, 'static/avatars/lady-avatar.svg'), upload_to='static/avatars/'),
        ),
    ]
